use std::env;
use std::fs;
use std::path::PathBuf;

pub struct Risc0BuildOptions {
    manifest_dir: PathBuf,
}

impl Risc0BuildOptions {
    pub fn new() -> Self {
        let manifest_dir = env::var("CARGO_MANIFEST_DIR")
            .map(PathBuf::from)
            .expect("CARGO_MANIFEST_DIR not set");

        Self { manifest_dir }
    }

    pub fn build(self) {
        // Step 1: Get the package without metadata requirement
        // get_package expects a directory containing Cargo.toml
        let pkg = risc0_build::get_package(&self.manifest_dir);

        // Step 2: Build guest for zkvm target
        // get_target_dir expects the manifest file path
        let manifest_path = self.manifest_dir.join("Cargo.toml");
        let target_dir = risc0_build::get_target_dir(&manifest_path);
        let entries =
            risc0_build::build_package(&pkg, &target_dir, risc0_build::GuestOptions::default())
                .expect("Failed to build guest package");

        // Step 3: Generate guest_methods.rs file
        self.generate_methods_file(&entries);

        // Step 4: Set up cargo rebuild triggers
        println!("cargo:rerun-if-changed=src/");
        println!("cargo:rerun-if-changed=Cargo.toml");
    }

    fn generate_methods_file(&self, entries: &[risc0_build::GuestListEntry]) {
        let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
        let methods_file = PathBuf::from(&out_dir).join("guest_methods.rs");

        let mut content = String::new();

        // Add header comment
        content.push_str("// Auto-generated by univm-build. Do not edit.\n\n");

        for entry in entries {
            let name = entry.name.to_uppercase().replace('-', "_");

            // Generate ELF constant
            content.push_str(&format!(
                "/// The ELF binary for the {} guest program.\n",
                entry.name
            ));
            content.push_str(&format!(
                "pub static {}_ELF: &[u8] = &{:?};\n\n",
                name,
                entry.elf.as_ref()
            ));

            // Generate ImageID constant
            content.push_str(&format!(
                "/// The ImageID for the {} guest program.\n",
                entry.name
            ));
            content.push_str(&format!(
                "pub static {}_ID: [u32; 8] = {:?};\n\n",
                name,
                entry.image_id.as_words()
            ));
        }

        fs::write(&methods_file, content).expect("Failed to write guest_methods.rs");

        println!(
            "cargo:warning=Generated guest_methods.rs at {:?}",
            methods_file
        );
    }
}

impl Default for Risc0BuildOptions {
    fn default() -> Self {
        Self::new()
    }
}
